import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#f9fafb',
    paddingVertical: 12,
  },
  rootDark: {
    backgroundColor: '#121212',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    margin: 10,
    padding: 18,
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 4,
  },
  cardDark: {
    backgroundColor: '#18181b',
    shadowColor: '#000',
    shadowOpacity: 0.25,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  backButton: {
    padding: 10,
    marginRight: 10,
    borderRadius: 24,
    backgroundColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#e5e7eb',
    marginRight: 14,
    borderWidth: 2,
    borderColor: '#22c55e',
  },
  author: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 2,
  },
  authorDark: {
    color: '#f3f4f6',
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  timeText: {
    fontSize: 13,
    color: '#6b7280',
  },
  timeTextDark: {
    color: '#d1d5db',
  },
  mainImg: {
    width: '100%',
    height: width * 0.55,
    borderRadius: 16,
    marginBottom: 18,
    backgroundColor: '#f3f4f6',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  stat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  statCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  green400: { 
    color: '#4ade80',
    fontWeight: '600',
  },
  green600: { 
    color: '#22c55e',
    fontWeight: '600',
  },
  gray200: { color: '#e5e7eb' },
  black: { color: '#111827' },
  divider: {
    height: 1.5,
    backgroundColor: '#e5e7eb',
    marginVertical: 14,
    borderRadius: 2,
  },
  dividerDark: {
    backgroundColor: '#374151',
  },
  btnRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
    gap: 10,
  },
  btn: {
    flex: 1,
    backgroundColor: '#22c55e',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    marginHorizontal: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 3,
  },
  btnWide: {
    flex: 2,
  },
  btnLabel: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 6,
  },
  btnActive: {
    backgroundColor: '#f9fafb',
    borderWidth: 1.5,
    borderColor: '#e11d48',
  },
  btnLabelActive: {
    color: '#e11d48',
  },
  list: {
    marginTop: 18,
    marginBottom: 10,
  },
  commentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  commentAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: '#22c55e',
    backgroundColor: '#e5e7eb',
  },
  commentBubble: {
    backgroundColor: '#f3f4f6',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    maxWidth: '85%',
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 3,
    elevation: 2,
  },
  commentBubbleDark: {
    backgroundColor: '#23272e',
  },
  commentText: {
    fontSize: 15,
    color: '#111827',
    lineHeight: 21,
  },
  commentTextDark: {
    color: '#f3f4f6',
  },
  commentAuthor: {
    fontSize: 14,
    fontWeight: '700',
    color: '#22c55e',
    marginBottom: 4,
  },
  commentAuthorDark: {
    color: '#4ade80',
  },
  commentTime: {
    fontSize: 12,
    color: '#9ca3af',
    marginTop: 4,
  },
  commentInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 10,
  },
  commentInput: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: '#22c55e',
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 12,
    fontSize: 15,
    backgroundColor: '#fff',
    color: '#111827',
  },
  commentInputDark: {
    borderColor: '#374151',
    backgroundColor: '#23272e',
    color: '#fff',
  },
  sendButton: {
    marginLeft: 10,
    backgroundColor: '#22c55e',
    borderRadius: 24,
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 2,
    elevation: 2,
  },
  sendButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  errorText: {
    color: '#ef4444',
    marginTop: 10,
    fontSize: 15,
    textAlign: 'center',
  },
});