import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 48,
    maxWidth: 380,
    alignSelf: 'center',
  },
  backBtn: {
    marginBottom: 36,
    backgroundColor: '#22c55e',
    borderRadius: 12,
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#22c55e',
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  logoRow: {
    justifyContent: 'center',
    marginBottom: 28,
  },
  logoText: {
    fontWeight: 'bold',
    fontSize: 36,
    flexDirection: 'row',
    alignItems: 'center',
  },
  subtitle: {
    textAlign: 'center',
    marginBottom: 36,
    fontSize: 16,
    fontWeight: '600',
    color: '#22c55e',
    letterSpacing: 0.2,
  },
  formGroup: {
    width: '100%',
    marginBottom: 28,
  },
  label: {
    color: '#22c55e',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
  },
  input: {
    width: '100%',
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 10,
    fontSize: 15,
    marginBottom: 14,
    borderWidth: 1.5,
  },
  inputDark: {
    borderColor: '#22c55e',
    color: '#fff',
    backgroundColor: '#23272e',
  },
  inputLight: {
    borderColor: '#22c55e',
    color: '#000',
    backgroundColor: '#fff',
  },
  forgotText: {
    color: '#22c55e',
    fontSize: 13,
    marginBottom: 18,
    textDecorationLine: 'underline',
    fontWeight: '500',
  },
  loginBtn: {
    width: '100%',
    backgroundColor: '#22c55e',
    borderRadius: 10,
    paddingVertical: 14,
    marginTop: 4,
    shadowColor: '#22c55e',
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 2,
  },
  loginText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 18,
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  orRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 28,
  },
  orLine: {
    flex: 1,
    borderBottomWidth: 1.5,
    borderColor: '#d1d5db',
  },
  orText: {
    marginHorizontal: 14,
    fontSize: 13,
    color: '#6b7280',
    fontWeight: '600',
  },
  googleBtn: {
    width: '100%',
    borderWidth: 1.5,
    borderRadius: 999,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
    backgroundColor: '#fff',
    borderColor: '#22c55e',
    shadowColor: '#22c55e',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  googleLogo: {
    width: 22,
    height: 22,
    marginRight: 10,
  },
  googleText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#22c55e',
  },
  registerRow: {
    textAlign: 'center',
    fontSize: 13,
    marginTop: 28,
    color: '#6b7280',
    fontWeight: '500',
  },
  registerLink: {
    color: '#22c55e',
    textDecorationLine: 'underline',
    marginLeft: 6,
    fontWeight: '700',
  },
});