import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 28,
    backgroundColor: '#f3f4f6',
  },
  containerDark: {
    backgroundColor: '#18181b',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 22,
  },
  backBtn: {
    backgroundColor: '#22c55e',
    borderRadius: 12,
    padding: 10,
    marginRight: 8,
    shadowColor: '#22c55e',
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 2,
  },
  headerText: {
    flex: 1,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 22,
    color: '#111827',
    letterSpacing: 0.2,
  },
  headerTextDark: {
    color: '#f3f4f6',
  },
  input: {
    borderWidth: 1.5,
    borderColor: '#22c55e',
    color: '#111827',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    width: '100%',
    marginBottom: 18,
    fontSize: 16,
  },
  inputDark: {
    borderColor: '#374151',
    color: '#fff',
    backgroundColor: '#232326',
  },
  sendBtn: {
    backgroundColor: '#22c55e',
    width: '100%',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#22c55e',
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  sendBtnText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 19,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  backIcon: {
    color: '#fff',
    fontSize: 20,
  },
});