import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f3f4f6',
    padding: 0,
  },
  containerDark: {
    backgroundColor: '#18181b',
  },
  scrollView: {
    flex: 1,
    padding: 24,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 28,
    paddingHorizontal: 4,
  },
  headerBtn: {
    backgroundColor: '#22c55e',
    padding: 14,
    borderRadius: 14,
    shadowColor: '#22c55e',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#18181b',
    letterSpacing: 0.2,
  },
  headerTitleDark: {
    color: '#fff',
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIconBtnDark: {
    borderColor: '#374151',
  },
  headerIconBtnLight: {
    borderColor: '#d1d5db',
  },
  profileInfo: {
    alignItems: 'center',
    marginBottom: 28,
  },
  profileAvatarBorder: {
    borderRadius: 999,
    borderWidth: 3,
    borderColor: '#22c55e',
    padding: 3,
    marginBottom: 14,
  },
  profileAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },
  profileName: {
    fontWeight: '700',
    fontSize: 20,
    marginBottom: 6,
    color: '#18181b',
  },
  profileNameDark: {
    color: '#fff',
  },
  profileEmail: {
    fontSize: 15,
    color: '#9ca3af',
    marginBottom: 2,
  },
  btnRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 28,
  },
  chatBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1.5,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginRight: 14,
  },
  chatBtnDark: {
    borderColor: '#374151',
  },
  chatBtnLight: {
    borderColor: '#d1d5db',
  },
  chatBtnText: {
    fontSize: 15,
    marginLeft: 10,
    color: '#374151',
    fontWeight: '600',
  },
  chatBtnTextDark: {
    color: '#e5e7eb',
  },
  followBtn: {
    backgroundColor: '#22c55e',
    borderRadius: 999,
    paddingHorizontal: 24,
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    shadowColor: '#22c55e',
    shadowOpacity: 0.10,
    shadowRadius: 5,
    elevation: 2,
  },
  followBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
    letterSpacing: 0.2,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
    paddingHorizontal: 4,
  },
  statBox: {
    flex: 1,
    alignItems: 'center',
    borderWidth: 1.5,
    borderRadius: 14,
    paddingVertical: 18,
    marginHorizontal: 6,
    backgroundColor: '#fff',
    shadowColor: '#22c55e',
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  statBoxDark: {
    borderColor: '#374151',
    backgroundColor: '#23272e',
  },
  statBoxLight: {
    borderColor: '#e5e7eb',
  },
  statNumber: {
    fontSize: 22,
    fontWeight: '700',
    color: '#18181b',
  },
  statNumberDark: {
    color: '#fff',
  },
  statLabel: {
    fontSize: 13,
    color: '#9ca3af',
    fontWeight: '600',
  },
  divider: {
    borderBottomWidth: 1.5,
    marginBottom: 28,
  },
  dividerDark: {
    borderColor: '#374151',
  },
  dividerLight: {
    borderColor: '#e5e7eb',
  },
  galleryTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 18,
    color: '#111827',
  },
  galleryTitleDark: {
    color: '#f3f4f6',
  },
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  galleryItem: {
    width: (width - 48) / 3,
    height: (width - 48) / 3,
    marginBottom: 10,
    borderRadius: 10,
    overflow: 'hidden',
  },
  galleryImage: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  emptyText: {
    textAlign: 'center',
    marginVertical: 24,
    color: '#6b7280',
    fontSize: 17,
    fontWeight: '500',
  },
  emptyTextDark: {
    color: '#9ca3af',
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
    borderRadius: 10,
    paddingVertical: 14,
    marginBottom: 28,
    borderWidth: 1.5,
    borderColor: '#e5e7eb',
    shadowColor: '#ef4444',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  logoutBtnDark: {
    backgroundColor: '#27272a',
    borderColor: '#374151',
  },
  logoutBtnText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#ef4444',
    letterSpacing: 0.2,
  },
  logoutBtnTextDark: {
    color: '#f87171',
  },
  sideMenuOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    zIndex: 1,
  },
  sideMenu: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: width * 0.75,
    backgroundColor: '#fff',
    zIndex: 2,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  sideMenuDark: {
    backgroundColor: '#1f1f1f',
  },
  sideMenuHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  sideMenuTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#111827',
  },
  sideMenuTitleDark: {
    color: '#f3f4f6',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  menuItemText: {
    fontSize: 16,
    marginLeft: 15,
    color: '#111827',
    flex: 1,
  },
  menuItemTextDark: {
    color: '#f3f4f6',
  },
  toggleSwitch: {
    width: 50,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#d1d5db',
    padding: 2,
    justifyContent: 'center',
  },
  toggleSwitchActive: {
    backgroundColor: '#22c55e',
  },
  toggleBall: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  toggleBallActive: {
    transform: [{ translateX: 22 }],
  },
});