import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    padding: 28,
    flex: 1,
    backgroundColor: '#f3f4f6',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 28,
    paddingVertical: 10,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#18181b',
    letterSpacing: 0.2,
  },
  backButton: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#e5e7eb',
    shadowColor: '#22c55e',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  avatarWrapper: {
    alignItems: 'center',
    marginBottom: 28,
    position: 'relative',
    borderWidth: 2,
    borderColor: '#22c55e',
    borderRadius: 64,
    padding: 6,
    alignSelf: 'center',
    backgroundColor: '#fff',
    shadowColor: '#22c55e',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  avatarImg: {
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: '#e5e7eb',
  },
  changeAvatarButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#fff',
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderWidth: 1.5,
    borderColor: '#22c55e',
    elevation: 2,
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.18,
    shadowRadius: 2,
  },
  changeAvatarText: {
    color: '#22c55e',
    fontSize: 15,
    fontWeight: '700',
  },
  label: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4b5563',
    marginBottom: 8,
    marginTop: 16,
  },
  input: {
    borderWidth: 1.5,
    borderColor: '#22c55e',
    borderRadius: 10,
    marginBottom: 18,
    fontSize: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    color: '#18181b',
    backgroundColor: '#fff',
  },
  bioInput: {
    height: 100,
    textAlignVertical: 'top',
  },
  saveBtn: {
    marginTop: 28,
    backgroundColor: '#22c55e',
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.14,
    shadowRadius: 3,
  },
  saveBtnDisabled: {
    backgroundColor: '#86efac',
  },
  saveBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 18,
    letterSpacing: 0.2,
  },
  errorText: {
    color: '#ef4444',
    marginTop: 10,
    marginBottom: 10,
    fontSize: 15,
    textAlign: 'center',
  },
});